// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc_vmIbRP9SWDnQLAe6Ef8BMTCPOSM1Dc',
    appId: '1:231931394475:android:3773a6a5b2ee732ecbfaee',
    messagingSenderId: '231931394475',
    projectId: 'haravara-30826',
    databaseURL:
        'https://haravara-30826-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'haravara-30826.appspot.com',
  );

  //USING HARAVARA-TEST
  /*static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy6QFIvRSxa1y0pXmT_Qv7Hd3kslWntfg',
    appId: '1:831880447542:android:9d56f8843ae16411affa97',
    messagingSenderId: '831880447542',
    projectId: 'haravara-test',
    databaseURL: 'https://haravara-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'haravara-test.appspot.com',
  );*/

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKF-l9GiUZNQJYXa06kh17v0gFA1cJJGg',
    appId: '1:231931394475:ios:866c1a6b57d8a934cbfaee',
    messagingSenderId: '231931394475',
    projectId: 'haravara-30826',
    databaseURL:
        'https://haravara-30826-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'haravara-30826.appspot.com',
    iosBundleId: 'sk.kosiceregion.haravara',
  );

  // USING HARAVARA-TEST
  /* static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvjpdndjk9dApo5B5GDSaBczmyJCAAV7U',
    appId: '1:831880447542:ios:e0c41ffae8ec0cbdaffa97',
    messagingSenderId: '831880447542',
    projectId: 'haravara-test',
    databaseURL: 'https://haravara-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'haravara-test.appspot.com',
    iosBundleId: 'sk.kosiceregion.haravara',
  );*/
}
